apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: threadline-api
spec:
  minReplicas: 1
  maxReplicas: 2
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: threadline-web
spec:
  minReplicas: 1
  maxReplicas: 2
